export enum Role {
  ADMIN = 'ADMIN',
  MAGASINIER = 'MAGASINIER',
  CHEF_DEPOT = 'CHEF DEPOT',
  RECOUVREMENT = 'RECOUVREMENT',
  CONTROLEUR = 'CONTROLEUR',
  SUPERVISEUR_MAGASIN = 'SUPERVISEUR_MAGASIN'
} 