export enum Role {
  ADMIN = 'ADMIN',
  MAGASINIER = 'MAGASINIER',
  CHEF_DEPOT = 'CHEF DEPOT',
  RECOUVREMENT = 'RECOUVREMENT',
  CONTROLEUR = 'CONTROLEUR',
}

export enum InvoiceStatus {
  EN_ATTENTE = 'EN ATTENTE DE LIVRAISON',
  EN_COURS = 'EN COURS DE LIVRAISON',
  LIVREE = 'LIVREE',
}
